const WORDS_DATA = [
{"group": "Exclamations", "category": "Ausrufe", "german": "Hilfe!", "english": "Help!", "pronunciation": "hil-fe"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Halt!", "english": "Stop!", "pronunciation": "halt"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Feuer!", "english": "Fire!", "pronunciation": "foy-er"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Vorsicht!", "english": "Careful!", "pronunciation": "for-ziht"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Viel Spaß!", "english": "Have fun!", "pronunciation": "fiil şpas"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Herzlich willkommen", "english": "Warm welcome / Welcome", "pronunciation": "herts-lih vil-kom-mın"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Entschuldigung!", "english": "Excuse me!", "pronunciation": "ent-şul-di-gung"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Einen Augenblick, bitte.", "english": "One moment, please.", "pronunciation": "ay-nın au-gen-blik bi-te"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Gesundheit!", "english": "Bless you!", "pronunciation": "ge-zunt-hayt"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Gute Besserung!", "english": "Get well soon!", "pronunciation": "gu-te be-se-rung"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Viel Glück!", "english": "Good luck!", "pronunciation": "fiil glük"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Viel Erfolg!", "english": "Much success!", "pronunciation": "fiil er-folk"},
{"group": "Exclamations", "category": "Ausrufe", "german": "Gute Reise!", "english": "Have a good trip!", "pronunciation": "guu-te ray-ze"},
{"group": "Expressions", "category": "Redewendungen", "german": "nach und nach", "english": "bit by bit", "pronunciation": "naah unt naah"},
{"group": "Expressions", "category": "Redewendungen", "german": "Schritt für Schritt", "english": "step by step", "pronunciation": "şrit für şrit"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Guten Morgen!", "english": "Good morning!", "pronunciation": "gu-tın mor-gen"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Guten Tag!", "english": "Good afternoon!", "pronunciation": "gu-tın taag"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Guten Abend!", "english": "Good evening!", "pronunciation": "gu-tın a-bent"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Gute Nacht!", "english": "Good night!", "pronunciation": "gu-te naht"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich bin _.", "english": "I am _.", "pronunciation": "ih bin"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Mein name ist _.", "english": "My name is _.", "pronunciation": "mayn naa-me ist"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich heiße _.", "english": "My name is _.", "pronunciation": "ih hay-se"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wer bist du?", "english": "Who are you?", "pronunciation": "ver bist du"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wie ist dein Name?", "english": "What is your name? (informal)", "pronunciation": "vii ist dayn naa-me"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wie ist Ihr Name?", "english": "What is your name? (formal)", "pronunciation": "vii ist iir naa-me"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wie heißt du?", "english": "What's your name?", "pronunciation": "vii hayst du"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Freut mich.", "english": "Nice to meet you. / I am pleased.", "pronunciation": "froyt mih"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Bist du Hans?", "english": "Are you Hans?", "pronunciation": "bist du hans?"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ist dein Name Hans?", "english": "Is your name Hans?", "pronunciation": "ist dayn naa-me hans?"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich bin Ausländer.", "english": "I am a foreigner.", "pronunciation": "ih bin aus-len-der"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wie geht es Ihnen?", "english": "How are you? (formal)", "pronunciation": "vii geyt es ii-nın"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wie geht es dir?", "english": "How are you? (informal)", "pronunciation": "vii geyt es diir"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wie geht's?", "english": "How are you? (informal)", "pronunciation": "vii geets"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Gut, danke! Und dir?", "english": "Fine, thanks! And you?", "pronunciation": "guut dan-ke! unt diir?"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Mir geht es gut.", "english": "I'm fine.", "pronunciation": "miir geet es guut"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Mir geht es schlecht.", "english": "I'm not so good.", "pronunciation": "miir geet es şleht"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wo kommst du her?", "english": "Where do you come from?", "pronunciation": "vo komst du heer"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Woher kommst du?", "english": "Where are you from?", "pronunciation": "vo-heer komst du"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich komme aus der Türkei.", "english": "I come from Turkey.", "pronunciation": "ih kom-me aus der tür-kay"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich komme nicht aus Deutschland.", "english": "I don't come from Germany.", "pronunciation": "ih kom-me niht aus doytç-lant"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich komme aus Frankreich.", "english": "I come from France.", "pronunciation": "ih kom-me aus frank-rayh"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich komme aus den Niederlanden.", "english": "I come from the Netherlands.", "pronunciation": "ih kom-me aus deen ni-der-lan-den"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich komme aus der Schweiz.", "english": "I come from Switzerland.", "pronunciation": "ih kom-me aus der şvayts"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wo wohnst du?", "english": "Where do you live?", "pronunciation": "vo vonst du"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich wohne in Istanbul.", "english": "I live in Istanbul.", "pronunciation": "ih voo-ne in is-tan-bul"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich wohne nicht in Berlin.", "english": "I don't live in Berlin.", "pronunciation": "ih voo-ne niht in ber-liin"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Was ist dein Beruf?", "english": "What is your profession?", "pronunciation": "vas ist dayn be-ruuf"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Was bist du von Beruf?", "english": "What are you by profession?", "pronunciation": "vas bist du fon be-ruuf"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Was machst du beruflich?", "english": "What do you do professionally?", "pronunciation": "vas mahst du be-ruuf-lih"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wie alt bist du?", "english": "How old are you?", "pronunciation": "vii alt bist du"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich bin 25 Jahre alt.", "english": "I am 25 years old.", "pronunciation": "ih bin fünüf-unt-tsvan-tsih yaa-re alt"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wo bist du geboren?", "english": "Where were you born?", "pronunciation": "vo bist du ge-bo-ren"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Welche Sprachen sprechen Sie?", "english": "Which languages do you speak? (formal)", "pronunciation": "vel-he şp-raa-hın şp-re-hın zii"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Ich spreche ein bisschen Deutsch.", "english": "I speak a little German.", "pronunciation": "ih şpre-he ayn bis-hın doytç"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wie viele Kinder hast du?", "english": "How many children do you have?", "pronunciation": "vii fii-le kin-der hast du"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Wie viele Bücher hast du?", "english": "How many books do you have?", "pronunciation": "vii fii-le bü-her hast du"},
{"group": "Greetings", "category": "Begrüßungen", "german": "danke", "english": "thank you", "pronunciation": "dan-ke"},
{"group": "Greetings", "category": "Begrüßungen", "german": "bitte", "english": "please / you’re welcome", "pronunciation": "bit-te"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Bis bald", "english": "see you soon", "pronunciation": "bis balt"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Bis später", "english": "see you later", "pronunciation": "bis şpee-tır"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Auf Wiedersehen", "english": "goodbye", "pronunciation": "auf vii-dır-zey-hın"},
{"group": "Greetings", "category": "Begrüßungen", "german": "Tschüss", "english": "bye", "pronunciation": "tşüüs"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Ich habe Hunger.", "english": "I'm hungry.", "pronunciation": "ih haa-be hun-ger"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Ich habe Durst.", "english": "I am thirsty. ", "pronunciation": "ih haa-be durst"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Ich bin müde.", "english": "I am tired.", "pronunciation": "ih bin mü-de"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Mir ist kalt.", "english": "I am cold. ", "pronunciation": "miir ist kalt"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Mir ist warm.", "english": "I am warm.", "pronunciation": "miir ist varm"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Tut mir Leid.", "english": "I'm sorry.", "pronunciation": "tuut miir layd"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Ich mag dich.", "english": "I like you.", "pronunciation": "ih maag dih"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Ich liebe dich.", "english": "I love you.", "pronunciation": "ih lii-be dih"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Ich wache um sechs Uhr auf.", "english": "I wake up at six o'clock.", "pronunciation": "ih va-he um zeks uur auf"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Ich stehe um sieben Uhr auf.", "english": "I get up at seven o'clock.", "pronunciation": "ih şte-he um zii-bın uur auf"},
{"group": "Feelings & States", "category": "Gefühle & Zustände", "german": "Der Kurs beginnt um halb elf.", "english": "The course starts at ten thirty.", "pronunciation": "der kurs be-gin-nın um halp elf"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Was machst du?", "english": "What are you doing?", "pronunciation": "vas mahst du"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Wann kommst du?", "english": "When are you coming?", "pronunciation": "van komst du"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Wie viel kostet das?", "english": "How much does that cost?", "pronunciation": "vii fiil kos-tet das"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Wie viel Zeit hast du?", "english": "How much time do you have?", "pronunciation": "vii fiil tsayt hast du"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Wie viele Hunde sind da?", "english": "How many dogs are there?", "pronunciation": "vii fii-le hun-de zint daa"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ist das richtig?", "english": "Ist ist right?", "pronunciation": "ist das rih-tih"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich spreche kein Deutsch.", "english": "I do not speak German.", "pronunciation": "ih şpre-he kayn doyç"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich verstehe gar nichts.", "english": "I don't understand anything.", "pronunciation": "ih fer-ştee-e gar nihts"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich verstehe dich nicht.", "english": "I don't understand you.", "pronunciation": "ih fer-ştee-e dih niht"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich verstehe dich gut.", "english": "I understand you well.", "pronunciation": "ih fer-ştee-e dih guut"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich weiß es nicht.", "english": "I don't know (it).", "pronunciation": "ih vays es niht"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich habe keine Ahnung.", "english": "I have no idea.", "pronunciation": "ih haa-be kay-ne aa-nung"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Können Sie langsamer sprechen, bitte?", "english": "Could you speak more slowly, please?", "pronunciation": "kö-nen zii lang-za-mer şpre-hen bi-te"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich kenne das nicht.", "english": "I don't know/am not familiar with that.", "pronunciation": "ih ken-ne das niht"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich kenne ihn/sie nicht.", "english": "I don't know him/her.", "pronunciation": "ih ken-ne iin/zii niht"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Sprich bitte langsamer.", "english": "Please speak slower.", "pronunciation": "şprih bi-te lang-za-mer"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Sprich bitte lauter.", "english": "Please speak louder.", "pronunciation": "şprih bi-te lau-ter"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Was heißt das?", "english": "What does it mean?", "pronunciation": "vas hayst das"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Können Sie mir helfen?", "english": "Can you help me? (formal)", "pronunciation": "kö-nen zii miir hel-fen"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Kannst du mir helfen?", "english": "Can you help me? (informal)", "pronunciation": "kanst du miir hel-fen"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich antworte ihm.", "english": "I answer him.", "pronunciation": "ih ant-vor-te iim"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich glaube dir.", "english": "I believe you.", "pronunciation": "ih glau-be diir"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich habe kein Geld.", "english": "I have no money.", "pronunciation": "ih haa-be kayn gelt"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich habe keine Zeit.", "english": "I don't have any time.", "pronunciation": "ih haa-be kay-ne tsayt"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Das ist nicht gut.", "english": "That is not good.", "pronunciation": "das ist niht guut"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich muss zur Toilette.", "english": "I have to go to the toilet.", "pronunciation": "ih mus tsur to-a-let-te"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich brauche eine Pause.", "english": "I need a break.", "pronunciation": "ih brau-he ay-ne pau-ze"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Können Sie das bitte aufschreiben?", "english": "Could you please write that down?", "pronunciation": "kö-nen zii das bi-te auf-şray-ben"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Schön dich zu sehen.", "english": "Nice to see you.", "pronunciation": "şön dih tsu ze-en"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich würde gerne ein/e ...  kaufen/bestellen.", "english": "I'd like to buy/order a …", "pronunciation": "ih vür-de ger-ne ayn/ay-ne kau-fen/be-ştel-len"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich würde gerne einen Porsche kaufen.", "english": "I'd like to buy a Porsche.", "pronunciation": "ih vür-de ger-ne ay-nen por-şe kau-fen"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich würde gerne ein Brötchen bestellen.", "english": "I'd like to order a bun.", "pronunciation": "ih vür-de ger-ne ayn bröt-hen be-ştel-len"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Kannst du mir sagen wo ich den Domplatz finde?", "english": "Can you tell me where I can find Domplatz?", "pronunciation": "kanst du miir zaa-gen voo ih den dom-plats fin-de"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Was hast du heute gemacht?", "english": "What have you done today?", "pronunciation": "vas hast du hoy-te ge-maht"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich würde mich gerne mit dir treffen.", "english": "I would like to meet up with you.", "pronunciation": "ih vür-de mih ger-ne mit diir tre-fen"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich würde gerne duschen.", "english": "I'd like to have a shower.", "pronunciation": "ih vür-de ger-ne du-şen"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Gibst du mir deine Handynummer?", "english": "Will you give me your mobile number?", "pronunciation": "gipst du miir day-ne hen-di-num-mer"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Was sind deine Träume?", "english": "What are your dreams?", "pronunciation": "vas zint day-ne troy-me"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Was hast du für Hobbies?", "english": "What are your hobbies?", "pronunciation": "vas hast du für ho-biis"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich kann gut kochen.", "english": "I can cook well.", "pronunciation": "ih kan guut ko-hen"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Fühlst du dich gut?", "english": "Do you feel OK?", "pronunciation": "fühlst du dih guut"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich habe keine Lust mehr.", "english": "I can't be bothered any more.", "pronunciation": "ih haa-be kay-ne lust meer"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Was macht du am Wochenende?", "english": "What are you doing at the weekend?", "pronunciation": "vas mahst du am vo-hen-en-de"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich mag das nicht.", "english": "I don't like that.", "pronunciation": "ih maag das niht"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Wie viel kostet das?", "english": "How much does … cost?", "pronunciation": "vii fiil kos-tet das"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich würde gerne bezahlen", "english": "I would like to pay.", "pronunciation": "ih vür-de ger-ne be-tsaa-len"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Könnte ich um die Rechnung bitten?", "english": "Could I have the bill please?", "pronunciation": "kön-te ih um dii reh-nung bi-ten"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Was für Musik hörst du?", "english": "What type of music do you listen to?", "pronunciation": "vas für mü-zik hörst du"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Die Sonne scheint.", "english": "The sun is shining.", "pronunciation": "dii zon-ne şaynt"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Es regnet heute.", "english": "It's raining today.", "pronunciation": "es reeg-net hoy-te"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Wo willst du hin (hingehen)?", "english": "Where do you want to go?", "pronunciation": "vo vilst du hin"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich gehe heute hin.", "english": "I'm going there today.", "pronunciation": "ih gee-e hoy-te hin"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich muss weg (weggehen).", "english": "I have to leave.", "pronunciation": "ih mus veg"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich will nach Hause.", "english": "I want to go home.", "pronunciation": "ih vil naah hau-ze"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Es ist sehr weit.", "english": "It's a long way.", "pronunciation": "es ist zeer vayt"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Muss ich links oder rechts abbiegen?", "english": "Do I have to turn left or right?", "pronunciation": "mus ih links oo-der rehts ab-bii-gen"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Geh nach rechts.", "english": "Go right.", "pronunciation": "gee naah rehts"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Geh nach links.", "english": "Go left.", "pronunciation": "gee naah links"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Geh geradeaus.", "english": "Go straight on.", "pronunciation": "gee ge-raa-de-aus"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Bitte warte auch mich.", "english": "Please wait for me. ", "pronunciation": "bi-te var-te auf mih"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich hätte gerne eine Brezel.", "english": "I would like a pretzel.", "pronunciation": "ih he-te ger-ne ay-ne bret-sel"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich hätte gerne einen Saft.", "english": "I would like some juice.", "pronunciation": "ih he-te ger-ne ay-nen zaft"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Haben Sie Kartoffeln?", "english": "Do you have potatoes?", "pronunciation": "haa-ben zii kar-tof-feln"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich bin bereit.", "english": "I am ready.", "pronunciation": "ih bin be-rayt"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Los geht's!", "english": "Let's go!", "pronunciation": "los geets"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Macht nichts.", "english": "It doesn't matter.", "pronunciation": "maht nihts"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich fahre.", "english": "I drive/go.", "pronunciation": "ih faa-re"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich bin gefahren.", "english": "I have driven/gone.", "pronunciation": "ih bin ge-faa-ren"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich fahre nach Spanien.", "english": "I am going to Spain.", "pronunciation": "ih faa-re naah şpaa-ni-yen"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich bin zum Flughafen gefahren.", "english": "I went to the airport.", "pronunciation": "ih bin tsum fluug-haa-fen ge-faa-ren"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Mein Buch ist neu.", "english": "My book is new.", "pronunciation": "mayn buuh ist noy"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ist dein Buch neu?", "english": "Is your book neu?", "pronunciation": "ist dayn buuh noy?"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Nein, mein Buch ist nicht neu.", "english": "No, my book is not new.", "pronunciation": "nayn mayn buuh ist niht noy"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich beginne um 09:00.", "english": "I start at 09:00.", "pronunciation": "ih be-gin-ne um noin uur"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Um 09:00 beginne ich.", "english": "At 09:00 I start.", "pronunciation": "um noin uur be-gin-ne ih"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Ich beende die Arbeit.", "english": "I finish the work.", "pronunciation": "ih be-en-de dii ar-bayt"},
{"group": "Daily conversation", "category": "Alltagsgespräche", "german": "Dann beende ich die Arbeit.", "english": "Then I finish the work.", "pronunciation": "dan be-en-de ih dii ar-bayt"},
{"group": "Time", "category": "Zeit", "german": "Wie spät ist es?", "english": "What time is it?", "pronunciation": "vii şpeet ist es?"},
{"group": "Time", "category": "Zeit", "german": "Wie viel Uhr ist es?", "english": "What time is it?", "pronunciation": "vii fiil uur ist es?"},
{"group": "Time", "category": "Zeit", "german": "Es ist zehn Uhr.", "english": "It is ten o'clock.", "pronunciation": "es ist tseen uur"},
{"group": "Time", "category": "Zeit", "german": "Es ist zwölf nach elf.", "english": "It is twelve past eleven.", "pronunciation": "es ist tsvölf nah elf"},
{"group": "Time", "category": "Zeit", "german": "Es ist Viertel nach zehn.", "english": "It is quarter past ten.", "pronunciation": "es ist fiir-tıl nah tseen"},
{"group": "Time", "category": "Zeit", "german": "Es ist zwölf nach elf.", "english": "It is twelve past eleven.", "pronunciation": "es ist tsvölf nah elf"},
{"group": "Time", "category": "Zeit", "german": "Es ist halb elf.", "english": "It is half past ten.", "pronunciation": "es ist halp elf"},
{"group": "Time", "category": "Zeit", "german": "Es ist zehn Uhr vierzig.", "english": "It is ten forty.", "pronunciation": "es ist tseen uur fiir-tsih"},
{"group": "Time", "category": "Zeit", "german": "Es ist zwanzig vor elf.", "english": "It is twenty to eleven.", "pronunciation": "es ist tsvan-tsih foor elf"},
{"group": "Time", "category": "Zeit", "german": "Es ist Viertel vor elf.", "english": "It is quarter to eleven.", "pronunciation": "es ist fiir-tıl foor elf"},
{"group": "Time", "category": "Zeit", "german": "die Uhr", "english": "the clock / watch", "pronunciation": "dii uur"},
{"group": "Time", "category": "Zeit", "german": "die Stunde", "english": "the hour (duration)", "pronunciation": "dii ştun-de"},
{"group": "Time", "category": "Zeit", "german": "nach", "english": "after / past", "pronunciation": "nah"},
{"group": "Time", "category": "Zeit", "german": "vor", "english": "before / to", "pronunciation": "foor"},
{"group": "Time", "category": "Zeit", "german": "halb", "english": "half", "pronunciation": "halp"},
{"group": "Time", "category": "Zeit", "german": "Viertel", "english": "quarter", "pronunciation": "fiir-tıl"},
{"group": "Time", "category": "Zeit", "german": "die Minute", "english": "the minute", "pronunciation": "dii mi-nuu-te"},
{"group": "Time", "category": "Zeit", "german": "die Sekunde", "english": "the second", "pronunciation": "dii ze-kun-de"},
{"group": "Time", "category": "Zeit", "german": "jetzt", "english": "now", "pronunciation": "yetst"},
{"group": "Time", "category": "Zeit", "german": "spät", "english": "late", "pronunciation": "şpeet"},
{"group": "Time", "category": "Zeit", "german": "früh", "english": "early", "pronunciation": "früü"},
{"group": "Time", "category": "Zeit", "german": "zuerst", "english": "first / firstly", "pronunciation": "tsu-eerst"},
{"group": "Time", "category": "Zeit", "german": "dann", "english": "then", "pronunciation": "dan"},
{"group": "Time", "category": "Zeit", "german": "danach", "english": "after that", "pronunciation": "da-nah"},
{"group": "Professions", "category": "Berufe", "german": "Ich bin kein Student.", "english": "I am not student.", "pronunciation": "ih bin kayn ştu-dent"},
{"group": "Professions", "category": "Berufe", "german": "Ich bin Ingenieur.", "english": "I am an engineer.", "pronunciation": "ih bin in-je-nyör"},
{"group": "Professions", "category": "Berufe", "german": "Ich bin Chemiker.", "english": "I am a chemist.", "pronunciation": "ih bin he-mi-ker"},
{"group": "Professions", "category": "Berufe", "german": "Ich bin Auditor.", "english": "I am an auditor.", "pronunciation": "ih bin au-di-tor"},
{"group": "Professions", "category": "Berufe", "german": "Ich arbeite als auditor.", "english": "I work as an auditor.", "pronunciation": "ih ar-bay-te als au-di-tor"},
{"group": "the adjective", "category": "das Adjektiv", "german": "ledig", "english": "single", "pronunciation": "ley-dih"},
{"group": "the adjective", "category": "das Adjektiv", "german": "verheiratet", "english": "married", "pronunciation": "fer-hay-ra-tet"},
{"group": "the adjective", "category": "das Adjektiv", "german": "krank", "english": "sick / ill", "pronunciation": "krank"},
{"group": "the adjective", "category": "das Adjektiv", "german": "schlect", "english": "bad", "pronunciation": "şleht"},
{"group": "the adjective", "category": "das Adjektiv", "german": "bereit", "english": "ready", "pronunciation": "be-rayt"},
{"group": "the adjective", "category": "das Adjektiv", "german": "müde", "english": "tired", "pronunciation": "mü-de"},
{"group": "the adjective", "category": "das Adjektiv", "german": "neu", "english": "new", "pronunciation": "noy"},
{"group": "the adjective", "category": "das Adjektiv", "german": "alt", "english": "old", "pronunciation": "alt"},
{"group": "the adjective", "category": "das Adjektiv", "german": "ein bisschen", "english": "a little bit", "pronunciation": "ayn bis-hın"},
{"group": "the adjective", "category": "das Adjektiv", "german": "groß", "english": "big / tall", "pronunciation": "groos"},
{"group": "the adjective", "category": "das Adjektiv", "german": "klein", "english": "small", "pronunciation": "klayn"},
{"group": "the adjective", "category": "das Adjektiv", "german": "arbeitslos", "english": "unemployed", "pronunciation": "ar-bayts-los"},
{"group": "the adjective", "category": "das Adjektiv", "german": "wichtige", "english": "important", "pronunciation": "vih-ti-ge"},
{"group": "the adjective", "category": "das Adjektiv", "german": "schwer", "english": "difficult", "pronunciation": "şveer"},
{"group": "the adjective", "category": "das Adjektiv", "german": "wunderschön", "english": "wonderful / beautiful", "pronunciation": "vun-der-şön"},
{"group": "the adjective", "category": "das Adjektiv", "german": "teuer", "english": "expensive", "pronunciation": "toy-er"},
{"group": "the adjective", "category": "das Adjektiv", "german": "laut", "english": "loud / noisy", "pronunciation": "laut"},
{"group": "the adjective", "category": "das Adjektiv", "german": "voll", "english": "full / crowded", "pronunciation": "fol"},
{"group": "the adjective", "category": "das Adjektiv", "german": "richtig", "english": "correct / right", "pronunciation": "rih-tih"},
{"group": "the adjective", "category": "das Adjektiv", "german": "falsch", "english": "false / wrong", "pronunciation": "falş"},
{"group": "the adjective", "category": "das Adjektiv", "german": "korrekt", "english": "correct", "pronunciation": "kor-rekt"},
{"group": "the adjective", "category": "das Adjektiv", "german": "kompakt", "english": "compact", "pronunciation": "kom-pakt"},
{"group": "the adjective", "category": "das Adjektiv", "german": "einige", "english": "some", "pronunciation": "ay-ni-ge"},
{"group": "the adjective", "category": "das Adjektiv", "german": "wenige", "english": "few", "pronunciation": "vee-ni-ge"},
{"group": "the adjective", "category": "das Adjektiv", "german": "alle", "english": "all", "pronunciation": "al-le"},
{"group": "the adjective", "category": "das Adjektiv", "german": "unregelmäßige", "english": "irregular", "pronunciation": "un-ree-gıl-mes-si-ge"},
{"group": "the adjective", "category": "das Adjektiv", "german": "sehr", "english": "very", "pronunciation": "zeer"},
{"group": "the noun", "category": "das Nomen", "german": "der Vorname", "english": "the first name", "pronunciation": "der foor-naa-me"},
{"group": "the noun", "category": "das Nomen", "german": "der Familienname", "english": "the last name / surname", "pronunciation": "der fa-mii-li-yen-naa-me"},
{"group": "the noun", "category": "das Nomen", "german": "die Frau", "english": "the woman / Mrs.", "pronunciation": "dii frau"},
{"group": "the noun", "category": "das Nomen", "german": "der Herr", "english": "the man / Mr.", "pronunciation": "der her"},
{"group": "the noun", "category": "das Nomen", "german": "der Kollege", "english": "the colleague (male)", "pronunciation": "der kol-ley-ge"},
{"group": "the noun", "category": "das Nomen", "german": "der Freund", "english": "the friend (male)", "pronunciation": "der froynt"},
{"group": "the noun", "category": "das Nomen", "german": "die Adresse", "english": "the address", "pronunciation": "dii ad-res-se"},
{"group": "the noun", "category": "das Nomen", "german": "die Handynummer", "english": "the mobile number", "pronunciation": "dii hen-di-num-mır"},
{"group": "the noun", "category": "das Nomen", "german": "Die Rechnung", "english": "The bill", "pronunciation": "reeg-nung"},
{"group": "the noun", "category": "das Nomen", "german": "der Student", "english": "student (male)", "pronunciation": "deyr ştuu-dent"},
{"group": "the noun", "category": "das Nomen", "german": "die Studentin", "english": "student (female)", "pronunciation": "dii ştuu-den-tin"},
{"group": "the noun", "category": "das Nomen", "german": "das Jahr", "english": "the year", "pronunciation": "das yaar"},
{"group": "the noun", "category": "das Nomen", "german": "die Jahreszahl", "english": "the year (date)", "pronunciation": "dii yaa-res-tsaal"},
{"group": "the noun", "category": "das Nomen", "german": "das Morgen", "english": "the morning", "pronunciation": "das mor-gen"},
{"group": "the noun", "category": "das Nomen", "german": "Technische Universität Yıldız", "english": "Yıldız Technical University", "pronunciation": "teh-nii-şe ü-ni-ver-zi-tet yıl-dız"},
{"group": "the noun", "category": "das Nomen", "german": "das Geld", "english": "the money", "pronunciation": "das gelt"},
{"group": "the noun", "category": "das Nomen", "german": "die Zeit", "english": "the time", "pronunciation": "dii tsayt"},
{"group": "the noun", "category": "das Nomen", "german": "die Anzahl", "english": "the quantity / number", "pronunciation": "dii an-tsaal"},
{"group": "the noun", "category": "das Nomen", "german": "das Flugzeug", "english": "the airplane", "pronunciation": "das fluug-tsoyk"},
{"group": "the noun", "category": "das Nomen", "german": "der Flughafen", "english": "the airport", "pronunciation": "deyr fluug-haa-fen"},
{"group": "the noun", "category": "das Nomen", "german": "der Student", "english": "the student", "pronunciation": "deyr ştuu-dent"},
{"group": "the noun", "category": "das Nomen", "german": "der Beruf", "english": "the job / profession", "pronunciation": "deyr be-ruuf"},
{"group": "the noun", "category": "das Nomen", "german": "die Stadt", "english": "the city", "pronunciation": "dii ştat"},
{"group": "the noun", "category": "das Nomen", "german": "die Hauptstadt", "english": "the capital city", "pronunciation": "dii haupt-ştat"},
{"group": "the noun", "category": "das Nomen", "german": "der Arbeiter", "english": "the worker", "pronunciation": "deyr ar-bay-ter"},
{"group": "the noun", "category": "das Nomen", "german": "die Arbeit", "english": "the work / job", "pronunciation": "dii ar-bayt"},
{"group": "the noun", "category": "das Nomen", "german": "das Studium", "english": "the studies / degree", "pronunciation": "das ştuu-di-um"},
{"group": "the noun", "category": "das Nomen", "german": "die Universität", "english": "the university", "pronunciation": "dii ü-ni-ver-zi-tet"},
{"group": "the noun", "category": "das Nomen", "german": "der Schüler", "english": "Student (primary/high school)", "pronunciation": "deyr şüü-ler"},
{"group": "the noun", "category": "das Nomen", "german": "der Ingenieur", "english": "the engineer (male)", "pronunciation": "deyr in-je-nyör"},
{"group": "the noun", "category": "das Nomen", "german": "die Ingenieurin", "english": "the engineer (female)", "pronunciation": "dii in-je-nyö-rin"},
{"group": "the noun", "category": "das Nomen", "german": "der Arzt", "english": "the doctor (male)", "pronunciation": "deyr artst"},
{"group": "the noun", "category": "das Nomen", "german": "die Ärztin", "english": "the doctor (female)", "pronunciation": "dii erts-tin"},
{"group": "the noun", "category": "das Nomen", "german": "der Lehrer", "english": "the teacher (male)", "pronunciation": "deyr ley-rer"},
{"group": "the noun", "category": "das Nomen", "german": "die Lehrerin", "english": "the teacher (female)", "pronunciation": "dii ley-re-rin"},
{"group": "the noun", "category": "das Nomen", "german": "die Türkei", "english": "Turkey", "pronunciation": "dii tür-kay"},
{"group": "the noun", "category": "das Nomen", "german": "Deutschland", "english": "Germany", "pronunciation": "doytş-lant"},
{"group": "the noun", "category": "das Nomen", "german": "die Schweiz", "english": "Switzerland", "pronunciation": "dii şvayts"},
{"group": "the noun", "category": "das Nomen", "german": "Österreich", "english": "Austria", "pronunciation": "ös-ter-rayh"},
{"group": "the noun", "category": "das Nomen", "german": "Frankreich", "english": "France", "pronunciation": "frank-rayh"},
{"group": "the noun", "category": "das Nomen", "german": "die Niederlande", "english": "Netherlands", "pronunciation": "dii nii-der-lan-de"},
{"group": "the noun", "category": "das Nomen", "german": "Europa", "english": "Europe", "pronunciation": "oy-ro-pa"},
{"group": "the noun", "category": "das Nomen", "german": "die Grenze", "english": "the border", "pronunciation": "dii gren-tse"},
{"group": "the noun", "category": "das Nomen", "german": "die Sprache", "english": "the language", "pronunciation": "dii şp-raa-he"},
{"group": "the noun", "category": "das Nomen", "german": "Französisch", "english": "French (language)", "pronunciation": "fran-tsö-ziş"},
{"group": "the noun", "category": "das Nomen", "german": "Holländisch", "english": "Dutch (language)", "pronunciation": "hol-len-diş"},
{"group": "the noun", "category": "das Nomen", "german": "Spanien", "english": "Spain", "pronunciation": "şpaa-ni-yen"},
{"group": "the noun", "category": "das Nomen", "german": "Spanisch", "english": "Spanish", "pronunciation": "şpaa-niş"},
{"group": "the noun", "category": "das Nomen", "german": "Polen", "english": "Poland", "pronunciation": "po-len"},
{"group": "the noun", "category": "das Nomen", "german": "Polnisch", "english": "Polish", "pronunciation": "pol-niş"},
{"group": "the noun", "category": "das Nomen", "german": "Tschechien", "english": "Czechia", "pronunciation": "tşe-hi-yen"},
{"group": "the noun", "category": "das Nomen", "german": "Tschechisch", "english": "Czech", "pronunciation": "tşe-hiş"},
{"group": "the noun", "category": "das Nomen", "german": "Türkisch", "english": "Turkish", "pronunciation": "tür-kiş"},
{"group": "the noun", "category": "das Nomen", "german": "die Stadt", "english": "the city", "pronunciation": "dii ştat"},
{"group": "the noun", "category": "das Nomen", "german": "das Land", "english": "the country", "pronunciation": "das lant"},
{"group": "the noun", "category": "das Nomen", "german": "die Großstadt", "english": "the big city / metropolis", "pronunciation": "dii groos-ştat"},
{"group": "the noun", "category": "das Nomen", "german": "das Richtig", "english": "the right (thing)", "pronunciation": "das rih-ti-ge"},
{"group": "the noun", "category": "das Nomen", "german": "das Falsch", "english": "the wrong (thing)", "pronunciation": "das fal-şe"},
{"group": "the noun", "category": "das Nomen", "german": "die Fremdsprache", "english": "the foreign language", "pronunciation": "dii fremt-şpraa-he"},
{"group": "the noun", "category": "das Nomen", "german": "die Ahnung", "english": "the idea / inkling", "pronunciation": "dii aa-nung"},
{"group": "the noun", "category": "das Nomen", "german": "die Zahl", "english": "the number", "pronunciation": "dii tsaal"},
{"group": "the noun", "category": "das Nomen", "german": "das Verb", "english": "the verb", "pronunciation": "das verb"},
{"group": "the noun", "category": "das Nomen", "german": "die Person", "english": "the person", "pronunciation": "dii per-zoon"},
{"group": "the noun", "category": "das Nomen", "german": "die Tabelle", "english": "the table / chart", "pronunciation": "dii ta-bel-le"},
{"group": "the noun", "category": "das Nomen", "german": "der Name", "english": "the name", "pronunciation": "deyr naa-me"},
{"group": "the noun", "category": "das Nomen", "german": "die Frau", "english": "the woman", "pronunciation": "dii frau"},
{"group": "the noun", "category": "das Nomen", "german": "der Mann", "english": "the man", "pronunciation": "deyr man"},
{"group": "the noun", "category": "das Nomen", "german": "die Tasche", "english": "the bag", "pronunciation": "dii ta-şe"},
{"group": "the noun", "category": "das Nomen", "german": "das Buch", "english": "the book", "pronunciation": "das buuh"},
{"group": "the noun", "category": "das Nomen", "german": "das Geschlecht", "english": "the gender", "pronunciation": "das ge-şleht"},
{"group": "the noun", "category": "das Nomen", "german": "männlich", "english": "masculine", "pronunciation": "men-lih"},
{"group": "the noun", "category": "das Nomen", "german": "weiblich", "english": "feminine", "pronunciation": "vayp-lih"},
{"group": "the noun", "category": "das Nomen", "german": "sächlich", "english": "neuter", "pronunciation": "zeh-lih"},
{"group": "the noun", "category": "das Nomen", "german": "der Hund", "english": "the dog", "pronunciation": "deyr hunt"},
{"group": "the noun", "category": "das Nomen", "german": "die Katze", "english": "the cat", "pronunciation": "dii kat-se"},
{"group": "the noun", "category": "das Nomen", "german": "das Auto", "english": "the car", "pronunciation": "das au-to"},
{"group": "the noun", "category": "das Nomen", "german": "das Kind", "english": "the kid", "pronunciation": "das kind"},
{"group": "the noun", "category": "das Nomen", "german": "der Apfel", "english": "the apple", "pronunciation": "deyr ap-fel"},
{"group": "the noun", "category": "das Nomen", "german": "das Haustier", "english": "the pet", "pronunciation": "das haus-tiir"},
{"group": "the noun", "category": "das Nomen", "german": "die Frage", "english": "the question", "pronunciation": "dii fraa-ge"},
{"group": "the noun", "category": "das Nomen", "german": "die Antwort", "english": "the answer", "pronunciation": "dii ant-vort"},
{"group": "the noun", "category": "das Nomen", "german": "der Singular", "english": "the singular", "pronunciation": "deyr zin-gu-lar"},
{"group": "the noun", "category": "das Nomen", "german": "der Plural", "english": "the plural", "pronunciation": "deyr plu-ral"},
{"group": "the noun", "category": "das Nomen", "german": "die Einzahl", "english": "the singular (Germanic term)", "pronunciation": "dii ayn-tsaal"},
{"group": "the noun", "category": "das Nomen", "german": "die Mehrzahl", "english": "the plural (Germanic term)", "pronunciation": "dii meer-tsaal"},
{"group": "the noun", "category": "das Nomen", "german": "die Kategorie", "english": "the category", "pronunciation": "dii ka-te-go-rii"},
{"group": "the noun", "category": "das Nomen", "german": "die Liste", "english": "the list", "pronunciation": "dii lis-te"},
{"group": "the noun", "category": "das Nomen", "german": "das Beispiel", "english": "the example", "pronunciation": "das bay-şpiil"},
{"group": "the noun", "category": "das Nomen", "german": "die Form", "english": "the form", "pronunciation": "dii form"},
{"group": "the noun", "category": "das Nomen", "german": "der Schritt", "english": "the step", "pronunciation": "deyr şrit"},
{"group": "the noun", "category": "das Nomen", "german": "die Aussprache", "english": "the pronunciation", "pronunciation": "dii aus-şp-raa-he"},
{"group": "the noun", "category": "das Nomen", "german": "die Ausdrücke", "english": "the expressions", "pronunciation": "dii aus-drük-ke"},
{"group": "the noun", "category": "das Nomen", "german": "die Arbeit", "english": "the work / job", "pronunciation": "arbait"},
{"group": "the noun", "category": "das Nomen", "german": "die Sprache", "english": "the language", "pronunciation": "şprahı"},
{"group": "the noun", "category": "das Nomen", "german": "die Telefonnummer", "english": "the phone number", "pronunciation": "dii te-le-foon-num-mır"},
{"group": "the noun", "category": "das Nomen", "german": "die E-Mail-Adresse", "english": "the email address", "pronunciation": "dii ii-meyl-ad-res-se"},
{"group": "the noun", "category": "das Nomen", "german": "das Übungsbuch", "english": "the workbook / exercise book", "pronunciation": "das üü-bunks-buuh"},
{"group": "the noun", "category": "das Nomen", "german": "das Tafelbild", "english": "the board image / board work", "pronunciation": "das taa-fıl-bilt"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Zahlen", "english": "the numbers", "pronunciation": "dii tsaa-lın"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Sprachen", "english": "the languages", "pronunciation": "dii şp-raa-hın"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Antworten", "english": "the answers", "pronunciation": "antvortın"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Berufe", "english": "the professions", "pronunciation": "dii be-ruu-fe"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Arbeitszeiten", "english": "the working hours", "pronunciation": "dii ar-bayts-tsay-tın"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Sätze", "english": "the sentences", "pronunciation": "dii zet-se"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Studenten", "english": "the students", "pronunciation": "dii ştuu-den-ten"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Ingenieure", "english": "the engineers", "pronunciation": "dii in-je-nyö-re"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Ärzte", "english": "the doctors", "pronunciation": "dii erts-te"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Lehrer", "english": "the teachers", "pronunciation": "dii ley-rer"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Namen", "english": "the names", "pronunciation": "dii naa-men"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Bücher", "english": "the books", "pronunciation": "dii bü-her"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Hunde", "english": "the dogs", "pronunciation": "dii hun-de"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Katzen", "english": "the cats", "pronunciation": "dii kat-sen"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Autos", "english": "the cars", "pronunciation": "dii au-tos"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Kinder", "english": "the kids", "pronunciation": "dii kin-der"},
{"group": "plural nouns", "category": "Nomen im Plural", "german": "die Äpfel", "english": "the apples", "pronunciation": "dii ep-fel"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "der Montag", "english": "Monday", "pronunciation": "deyr mo:n-tag"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "der Dienstag", "english": "Tuesday", "pronunciation": "deyr di:ns-tag"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "der Mittwoch", "english": "Wednesday", "pronunciation": "deyr mit-voh"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "der Donnerstag", "english": "Thursday", "pronunciation": "deyr do-ners-tag"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "der Freitag", "english": "Friday", "pronunciation": "deyr frai-tag"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "der Samstag", "english": "Saturday", "pronunciation": "deyr zams-tag"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "der Sonntag", "english": "Sunday", "pronunciation": "deyr zon-tag"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "die Woche", "english": "the week", "pronunciation": "vo-he"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "die Wochentage", "english": "the weekdays", "pronunciation": "vo-hen-ta-ge"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "das Wochenende", "english": "the weekend", "pronunciation": "vo-hen-en-de"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "der Tag", "english": "the day", "pronunciation": "ta:k"},
{"group": "the noun - days", "category": "das Nomen - Tage", "german": "die Tage", "english": "the days", "pronunciation": "ta:-ge"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der Januar", "english": "January", "pronunciation": "ya-nu-ar"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der Februar", "english": "February", "pronunciation": "fe-bu-ar"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der März", "english": "March", "pronunciation": "merts"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der April", "english": "April", "pronunciation": "ap-ril"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der Mai", "english": "May", "pronunciation": "may"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der Juni", "english": "June", "pronunciation": "yu-ni"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der Juli", "english": "July", "pronunciation": "yu-li"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der August", "english": "August", "pronunciation": "au-gust"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der September", "english": "September", "pronunciation": "sep-tem-ber"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der Oktober", "english": "October", "pronunciation": "ok-to-ber"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der November", "english": "November", "pronunciation": "no-vem-ber"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der Dezember", "english": "December", "pronunciation": "de-tsem-ber"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "der Monat", "english": "the month", "pronunciation": "mo-nat"},
{"group": "the noun - months", "category": "das Nomen - Monate", "german": "die Monate", "english": "the months", "pronunciation": "mo-na-te"},
{"group": "the noun - seasons", "category": "das Nomen - Jahreszeiten", "german": "der Frühling", "english": "spring", "pronunciation": "fri-ling"},
{"group": "the noun - seasons", "category": "das Nomen - Jahreszeiten", "german": "der Sommer", "english": "summer", "pronunciation": "zo-mer"},
{"group": "the noun - seasons", "category": "das Nomen - Jahreszeiten", "german": "der Herbst", "english": "autumn", "pronunciation": "herpst"},
{"group": "the noun - seasons", "category": "das Nomen - Jahreszeiten", "german": "der Winter", "english": "winter", "pronunciation": "vin-ter"},
{"group": "the noun - seasons", "category": "das Nomen - Jahreszeiten", "german": "die Jahreszeit", "english": "the season", "pronunciation": "ya-res-tsayt"},
{"group": "the noun - seasons", "category": "das Nomen - Jahreszeiten", "german": "die Jahreszeiten", "english": "the seasons", "pronunciation": "ya-res-tsay-ten"},
{"group": "the verb", "category": "das Verb", "german": "hingehen", "english": "to go there / to a specific place", "pronunciation": "hin-gey-en"},
{"group": "the verb", "category": "das Verb", "german": "beginnen", "english": "to start / begin", "pronunciation": "be-gin-nın"},
{"group": "the verb", "category": "das Verb", "german": "beenden", "english": "to finish / to end", "pronunciation": "be-en-dın"},
{"group": "the verb", "category": "das Verb", "german": "aufstehen", "english": "to get up", "pronunciation": "auf-şte-hın"},
{"group": "the verb", "category": "das Verb", "german": "schlafen", "english": "to sleep", "pronunciation": "şlaa-fın"},
{"group": "the verb", "category": "das Verb", "german": "fertig sein", "english": "to be finished / ready", "pronunciation": "fer-tih zayn"},
{"group": "the verb", "category": "das Verb", "german": "aufwachen", "english": "to wake up", "pronunciation": "auf-va-hın"},
{"group": "the verb", "category": "das Verb", "german": "aufstehen", "english": "to get up", "pronunciation": "auf-şte-hın"},
{"group": "the verb", "category": "das Verb", "german": "kosten", "english": "to cost", "pronunciation": "kos-ten"},
{"group": "the verb", "category": "das Verb", "german": "studieren", "english": "to study (at university)", "pronunciation": "ştu-di-ren"},
{"group": "the verb", "category": "das Verb", "german": "lernen", "english": "to study / to learn", "pronunciation": "ler-nın"},
{"group": "the verb", "category": "das Verb", "german": "arbeiten", "english": "to work", "pronunciation": "ar-bay-ten"},
{"group": "the verb", "category": "das Verb", "german": "wohnen", "english": "to live / to reside", "pronunciation": "vo-nen"},
{"group": "the verb", "category": "das Verb", "german": "leben", "english": "to live (life)", "pronunciation": "ley-ben"},
{"group": "the verb", "category": "das Verb", "german": "haben", "english": "to have", "pronunciation": "haa-ben"},
{"group": "the verb", "category": "das Verb", "german": "sprechen", "english": "to speak", "pronunciation": "şpre-hen"},
{"group": "the verb", "category": "das Verb", "german": "wissen", "english": "to know (a fact)", "pronunciation": "vis-sen"},
{"group": "the verb", "category": "das Verb", "german": "kennen", "english": "to know (be familiar)", "pronunciation": "ken-nen"},
{"group": "the verb", "category": "das Verb", "german": "heißen", "english": "to be called / named", "pronunciation": "hay-sen"},
{"group": "the verb", "category": "das Verb", "german": "zählen", "english": "to count", "pronunciation": "tse-len"},
{"group": "the verb", "category": "das Verb", "german": "kopieren", "english": "to copy", "pronunciation": "ko-pi-ren"},
{"group": "the verb", "category": "das Verb", "german": "einfügen", "english": "to paste / to insert", "pronunciation": "ayn-fü-gen"},
{"group": "the verb", "category": "das Verb", "german": "ausschneiden", "english": "to cut", "pronunciation": "aus-şnay-den"},
{"group": "the verb", "category": "das Verb", "german": "speichern", "english": "to save", "pronunciation": "şpay-chern"},
{"group": "the verb", "category": "das Verb", "german": "löschen", "english": "to delete", "pronunciation": "lö-şen"},
{"group": "the verb", "category": "das Verb", "german": "hören", "english": "to hear / to listen", "pronunciation": "höö-rın"},
{"group": "the verb", "category": "das Verb", "german": "sehen", "english": "to see", "pronunciation": "zey-hın"},
{"group": "the verb", "category": "das Verb", "german": "üben", "english": "to practice", "pronunciation": "üü-bın"},
{"group": "the verb", "category": "das Verb", "german": "schreiben", "english": "to write", "pronunciation": "şray-bın"},
{"group": "the verb", "category": "das Verb", "german": "lösen", "english": "to solve", "pronunciation": "löö-zın"},
{"group": "the verb", "category": "das Verb", "german": "finden", "english": "to find", "pronunciation": "fin-dın"},
{"group": "the verb", "category": "das Verb", "german": "sagen", "english": "to say", "pronunciation": "zaa-gın"},
{"group": "the verb", "category": "das Verb", "german": "vergleichen", "english": "to compare", "pronunciation": "fer-glay-hın"},
{"group": "the verb", "category": "das Verb", "german": "ausfüllen", "english": "to fill in", "pronunciation": "aus-fül-lın"},
{"group": "the verb", "category": "das Verb", "german": "schreiben", "english": "to write", "pronunciation": "şraybın"},
{"group": "the verb", "category": "das Verb", "german": "buchstabieren", "english": "to spell", "pronunciation": "buh-şta-bii-rın"},
{"group": "the verb", "category": "das Verb", "german": "recherchieren", "english": "to research", "pronunciation": "re-şer-şii-rın"},
{"group": "the verb", "category": "das Verb", "german": "bekommen", "english": "to get / receive", "pronunciation": "be-kom-mın"},
{"group": "the verb", "category": "das Verb", "german": "vorstellen", "english": "to introduce", "pronunciation": "foor-ştel-lın"},
{"group": "the verb", "category": "das Verb", "german": "grüßen", "english": "to greet", "pronunciation": "grüü-sın"},
{"group": "the verb", "category": "das Verb", "german": "verabschieden", "english": "to say goodbye", "pronunciation": "fer-ap-şii-dın"},
{"group": "the verb", "category": "das Verb", "german": "ordnen", "english": "to arrange / to sort", "pronunciation": "ord-nın"},
{"group": "the verb", "category": "das Verb", "german": "besitzen", "english": "to possess / to own", "pronunciation": "be-zit-sen"},
{"group": "the verb", "category": "das Verb", "german": "gehören", "english": "to belong to", "pronunciation": "ge-hö-ren"},
{"group": "the verb", "category": "das Verb", "german": "fragen", "english": "to ask", "pronunciation": "fraa-gen"},
{"group": "the verb", "category": "das Verb", "german": "antworten", "english": "to answer", "pronunciation": "ant-vor-tın"},
{"group": "the verb", "category": "das Verb", "german": "lesen", "english": "to read", "pronunciation": "ley-zen"},
{"group": "the verb", "category": "das Verb", "german": "sortieren", "english": "to sort / to organize", "pronunciation": "zor-ti-ren"},
{"group": "the verb", "category": "das Verb", "german": "gehen", "english": "to walk / go on foot", "pronunciation": "gey-en"},
{"group": "the verb", "category": "das Verb", "german": "fahren", "english": "to drive / go by vehicle", "pronunciation": "faa-ren"},
{"group": "the verb", "category": "das Verb", "german": "fliegen", "english": "to fly", "pronunciation": "flii-gen"},
{"group": "the verb", "category": "das Verb", "german": "machen", "english": "to make/done", "pronunciation": "ma-hen"},
{"group": "the adverb", "category": "das Adverb", "german": "bis", "english": "until / to", "pronunciation": "bis"},
{"group": "the adverb", "category": "das Adverb", "german": "auch", "english": "also / too", "pronunciation": "auh"},
{"group": "the adverb", "category": "das Adverb", "german": "ganz", "english": "quite/ whole", "pronunciation": "gants"},
{"group": "the adverb", "category": "das Adverb", "german": "heute", "english": "today", "pronunciation": "hoy-te"},
{"group": "the adverb", "category": "das Adverb", "german": "morgen", "english": "tomorrow", "pronunciation": "mor-gen"},
{"group": "the adverb", "category": "das Adverb", "german": "gestern", "english": "yesterday", "pronunciation": "ges-tern"},
{"group": "the adverb", "category": "das Adverb", "german": "jetzt", "english": "now", "pronunciation": "yetst"},
{"group": "the adverb", "category": "das Adverb", "german": "sofort", "english": "immediately", "pronunciation": "zo-fort"},
{"group": "the adverb", "category": "das Adverb", "german": "früh", "english": "early", "pronunciation": "früü"},
{"group": "the adverb", "category": "das Adverb", "german": "viel", "english": "much / a lot", "pronunciation": "fiil"},
{"group": "the adverb", "category": "das Adverb", "german": "dort", "english": "there", "pronunciation": "dort"},
{"group": "the adverb", "category": "das Adverb", "german": "hier", "english": "here", "pronunciation": "hiir"},
{"group": "the adverb", "category": "das Adverb", "german": "da", "english": "there / here", "pronunciation": "daa"},
{"group": "the adverb", "category": "das Adverb", "german": "draußen", "english": "outside", "pronunciation": "drau-sen"},
{"group": "the adverb", "category": "das Adverb", "german": "drinnen", "english": "inside", "pronunciation": "drin-nen"},
{"group": "the adverb", "category": "das Adverb", "german": "viele", "english": "many", "pronunciation": "fii-le"},
{"group": "the adverb", "category": "das Adverb", "german": "mehr", "english": "more", "pronunciation": "meyr"},
{"group": "the adverb", "category": "das Adverb", "german": "beide", "english": "both", "pronunciation": "bay-de"},
{"group": "the adverb", "category": "das Adverb", "german": "langsam", "english": "slowly", "pronunciation": "lang-zam"},
{"group": "the adverb", "category": "das Adverb", "german": "zum", "english": "to the (masc/neut)", "pronunciation": "tsum"},
{"group": "the adverb", "category": "das Adverb", "german": "zur", "english": "to the (fem)", "pronunciation": "tsur"},
{"group": "the adverb", "category": "das Adverb", "german": "zusammen", "english": "together", "pronunciation": "tsu-zam-mın"},
{"group": "the adverb", "category": "das Adverb", "german": "anderen", "english": "other / others", "pronunciation": "an-de-rın"},
{"group": "the conjunction", "category": "die Konjunktion", "german": "und", "english": "and", "pronunciation": "unt"},
{"group": "the conjunction", "category": "die Konjunktion", "german": "aber", "english": "but", "pronunciation": "aa-ber"},
{"group": "the conjunction", "category": "die Konjunktion", "german": "oder", "english": "or", "pronunciation": "oo-der"},
{"group": "the preposition", "category": "die Präposition", "german": "nach", "english": "to (towards a country/city)", "pronunciation": "naah"},
{"group": "the preposition", "category": "die Präposition", "german": "mit", "english": "with", "pronunciation": "mit"},
{"group": "the preposition", "category": "die Präposition", "german": "von", "english": "of / from / by", "pronunciation": "fon"},
{"group": "the preposition", "category": "die Präposition", "german": "aus", "english": "from", "pronunciation": "aus"},
{"group": "the preposition", "category": "die Präposition", "german": "um", "english": "at", "pronunciation": "um"},
{"group": "the preposition", "category": "die Präposition", "german": "in", "english": "in", "pronunciation": "in"},

{"group": "the noun", "category": "das Nomen", "german": "der Buchstabe", "english": "the letter (alphabet)", "pronunciation": "der buuh-şta-be"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "A a", "english": "A a", "pronunciation": "aa"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "B b", "english": "B b", "pronunciation": "be"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "C c", "english": "C c", "pronunciation": "tse"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "D d", "english": "D d", "pronunciation": "de"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "E e", "english": "E e", "pronunciation": "ee"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "F f", "english": "F f", "pronunciation": "ef"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "G g", "english": "G g", "pronunciation": "ge"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "H h", "english": "H h", "pronunciation": "ha"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "I i", "english": "I i", "pronunciation": "ii"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "J j", "english": "J j", "pronunciation": "yot"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "K k", "english": "K k", "pronunciation": "ka"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "L l", "english": "L l", "pronunciation": "el"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "M m", "english": "M m", "pronunciation": "em"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "N n", "english": "N n", "pronunciation": "en"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "O o", "english": "O o", "pronunciation": "oo"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "P p", "english": "P p", "pronunciation": "pe"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "Q q", "english": "Q q", "pronunciation": "ku"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "R r", "english": "R r", "pronunciation": "er"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "S s", "english": "S s", "pronunciation": "es"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "T t", "english": "T t", "pronunciation": "te"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "U u", "english": "U u", "pronunciation": "uu"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "V v", "english": "V v", "pronunciation": "fau"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "W w", "english": "W w", "pronunciation": "ve"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "X x", "english": "X x", "pronunciation": "iks"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "Y y", "english": "Y y", "pronunciation": "üpsilon"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "Z z", "english": "Z z", "pronunciation": "tset"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "Ä ä", "english": "A-Umlaut", "pronunciation": "e"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "Ö ö", "english": "O-Umlaut", "pronunciation": "ö"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "Ü ü", "english": "U-Umlaut", "pronunciation": "ü"},
{"group": "the letter (alphabet)", "category": "der Buchstabe", "german": "ß", "english": "Eszett", "pronunciation": "es-tset"},

{"group": "the noun", "category": "das Nomen", "german": "Die Zahl", "english": "The number", "pronunciation": "dii tsaal"},
{"group": "The number", "category": "Die Zahl", "german": "null", "english": "zero", "pronunciation": "nul"},
{"group": "The number", "category": "Die Zahl", "german": "eins", "english": "one", "pronunciation": "aynts"},
{"group": "The number", "category": "Die Zahl", "german": "zwei", "english": "two", "pronunciation": "tsvay"},
{"group": "The number", "category": "Die Zahl", "german": "drei", "english": "three", "pronunciation": "dray"},
{"group": "The number", "category": "Die Zahl", "german": "vier", "english": "four", "pronunciation": "fiir"},
{"group": "The number", "category": "Die Zahl", "german": "fünf", "english": "five", "pronunciation": "fünüf"},
{"group": "The number", "category": "Die Zahl", "german": "sechs", "english": "six", "pronunciation": "zeks"},
{"group": "The number", "category": "Die Zahl", "german": "sieben", "english": "seven", "pronunciation": "ziibın"},
{"group": "The number", "category": "Die Zahl", "german": "acht", "english": "eight", "pronunciation": "aht"},
{"group": "The number", "category": "Die Zahl", "german": "neun", "english": "nine", "pronunciation": "noyn"},
{"group": "The number", "category": "Die Zahl", "german": "zehn", "english": "ten", "pronunciation": "tseyn"},
{"group": "The number", "category": "Die Zahl", "german": "elf", "english": "eleven", "pronunciation": "elf"},
{"group": "The number", "category": "Die Zahl", "german": "zwölf", "english": "twelve", "pronunciation": "tsvölf"},
{"group": "The number", "category": "Die Zahl", "german": "dreizehn", "english": "thirteen", "pronunciation": "dray-tseyn"},
{"group": "The number", "category": "Die Zahl", "german": "vierzehn", "english": "fourteen", "pronunciation": "fiir-tseyn"},
{"group": "The number", "category": "Die Zahl", "german": "fünfzehn", "english": "fifteen", "pronunciation": "fünf-tseyn"},
{"group": "The number", "category": "Die Zahl", "german": "sechzehn", "english": "sixteen", "pronunciation": "zeh-tseyn"},
{"group": "The number", "category": "Die Zahl", "german": "siebzehn", "english": "seventeen", "pronunciation": "ziib-tseyn"},
{"group": "The number", "category": "Die Zahl", "german": "achtzehn", "english": "eighteen", "pronunciation": "aht-tseyn"},
{"group": "The number", "category": "Die Zahl", "german": "neunzehn", "english": "nineteen", "pronunciation": "noyn-tseyn"},
{"group": "The number", "category": "Die Zahl", "german": "zwanzig", "english": "twenty", "pronunciation": "tsvan-tsih"},
{"group": "The number", "category": "Die Zahl", "german": "einundzwanzig", "english": "twenty-one", "pronunciation": "ayn-und-tsvantsig"},
{"group": "The number", "category": "Die Zahl", "german": "zweiundzwanzig", "english": "twenty-two", "pronunciation": "tsvay-und-tsvantsig"},
{"group": "The number", "category": "Die Zahl", "german": "dreiundzwanzig", "english": "twenty-three", "pronunciation": "dray-und-tsvantsig"},
{"group": "The number", "category": "Die Zahl", "german": "vierundzwanzig", "english": "twenty-four", "pronunciation": "fiir-und-tsvantsig"},
{"group": "The number", "category": "Die Zahl", "german": "fünfundzwanzig", "english": "twenty-five", "pronunciation": "fünf-und-tsvantsig"},
{"group": "The number", "category": "Die Zahl", "german": "sechsundzwanzig", "english": "twenty-six", "pronunciation": "zeks-und-tsvantsig"},
{"group": "The number", "category": "Die Zahl", "german": "siebenundzwanzig", "english": "twenty-seven", "pronunciation": "ziibın-und-tsvantsig"},
{"group": "The number", "category": "Die Zahl", "german": "achtundzwanzig", "english": "twenty-eight", "pronunciation": "aht-und-tsvantsig"},
{"group": "The number", "category": "Die Zahl", "german": "neunundzwanzig", "english": "twenty-nine", "pronunciation": "noyn-und-tsvantsig"},
{"group": "The number", "category": "Die Zahl", "german": "dreißig", "english": "thirty", "pronunciation": "dray-sih"},
{"group": "The number", "category": "Die Zahl", "german": "vierzig", "english": "forty", "pronunciation": "fiir-tsih"},
{"group": "The number", "category": "Die Zahl", "german": "fünfzig", "english": "fifty", "pronunciation": "fünf-tsih"},
{"group": "The number", "category": "Die Zahl", "german": "sechzig", "english": "sixty", "pronunciation": "zeh-tsih"},
{"group": "The number", "category": "Die Zahl", "german": "siebzig", "english": "seventy", "pronunciation": "ziib-tsih"},
{"group": "The number", "category": "Die Zahl", "german": "achtzig", "english": "eighty", "pronunciation": "aht-tsih"},
{"group": "The number", "category": "Die Zahl", "german": "neunzig", "english": "ninety", "pronunciation": "noyn-tsih"},
{"group": "The number", "category": "Die Zahl", "german": "hundert", "english": "hundred", "pronunciation": "hun-dert"},
{"group": "The number", "category": "Die Zahl", "german": "zweihundert", "english": "two hundred", "pronunciation": "tsvay-hun-dert"},
{"group": "The number", "category": "Die Zahl", "german": "dreihundert", "english": "three hundred", "pronunciation": "dray-hun-dert"},
{"group": "The number", "category": "Die Zahl", "german": "fünfhundert", "english": "five hundred", "pronunciation": "fünf-hun-dert"},
{"group": "The number", "category": "Die Zahl", "german": "einhunderttausend", "english": "one hundred thousand", "pronunciation": "ayn-hun-dert-tau-zınt"},
{"group": "The number", "category": "Die Zahl", "german": "eine Million", "english": "one million", "pronunciation": "ay-ne mil-yoon"},
{"group": "The number", "category": "Die Zahl", "german": "neunzehnhundertneunundachtzig", "english": "nineteen eighty-nine", "pronunciation": "noyn-tseyn-hun-dert-noyn-unt-aht-tsih"},
{"group": "The number", "category": "Die Zahl", "german": "zweitausendvier", "english": "two thousand and four", "pronunciation": "tsvay-tau-zınt-fiir"},
{"group": "The number", "category": "Die Zahl", "german": "zweitausendfünfzehn", "english": "two thousand and fifteen", "pronunciation": "tsvay-tau-zınt-fünf-tseyn"},
{"group": "The number", "category": "Die Zahl", "german": "zweitausendsechsundzwanzig", "english": "two thousand and twenty-six", "pronunciation": "tsvay-tau-zınt-zeks-unt-tsvantsig"},

{"group": "the verb", "category": "das Verb", "german": "Sein", "english": "To be", "pronunciation": "Zein"},
{"group": "the pronoun", "category": "das Pronomen", "german": "Ich bin", "english": "I am", "pronunciation": "ih bin"},
{"group": "the pronoun", "category": "das Pronomen", "german": "Du bist", "english": "You are", "pronunciation": "du bist"},
{"group": "the pronoun", "category": "das Pronomen", "german": "Er/Sie/Es ist", "english": "He/She/It is", "pronunciation": "er/zii/es ist"},
{"group": "the pronoun", "category": "das Pronomen", "german": "Wir sind", "english": "We are", "pronunciation": "viir zint"},
{"group": "the pronoun", "category": "das Pronomen", "german": "Ihr seid", "english": "You (all) are", "pronunciation": "iir zayt"},
{"group": "the pronoun", "category": "das Pronomen", "german": "Sie/sie sind", "english": "You (form.) / They are", "pronunciation": "zii zint"},

{"group": "the verb", "category": "das Verb", "german": "kommen", "english": "come", "pronunciation": "komın"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Ich komme", "english": "I come", "pronunciation": "ih kom-me"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Du kommst", "english": "You come", "pronunciation": "du komst"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Er/Sie/Es kommt", "english": "He/She/It comes", "pronunciation": "er/zii/es komt"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Wir kommen", "english": "We come", "pronunciation": "viir kom-mın"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Ihr kommt", "english": "You (all) come", "pronunciation": "iir komt"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Sie/sie kommen", "english": "You (form.)/They come", "pronunciation": "zii kom-mın"},

{"group": "the verb", "category": "das Verb", "german": "arbeiten", "english": "to work", "pronunciation": ""},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Ich arbeite", "english": "I work", "pronunciation": "ih ar-bay-te"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Du arbeitest", "english": "You work (informal)", "pronunciation": "du ar-bay-test"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Er/Sie/Es arbeitet", "english": "He/She/It works", "pronunciation": "er/zii/es ar-bay-tet"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Wir arbeiten", "english": "We work", "pronunciation": "viir ar-bay-tın"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Ihr arbeitet", "english": "You (all) work", "pronunciation": "iir ar-bay-tet"},
{"group": "Verb Conjugations", "category": "Verbkonjugationen", "german": "Sie/sie arbeiten", "english": "You (form.)/They work", "pronunciation": "zii ar-bay-tın"},

{"group": "the noun", "category": "das Nomen", "german": "Possessivpronomen", "english": "Possessive pronouns", "pronunciation": "possesivpronomın"},
{"group": "Possessive pronouns", "category": "Possessivpronomen", "german": "mein", "english": "my", "pronunciation": "mayn"},
{"group": "Possessive pronouns", "category": "Possessivpronomen", "german": "dein", "english": "your", "pronunciation": "dayn"},
{"group": "Possessive pronouns", "category": "Possessivpronomen", "german": "sein", "english": "his", "pronunciation": "zayn"},
{"group": "Possessive pronouns", "category": "Possessivpronomen", "german": "ihr", "english": "her", "pronunciation": "iir"},
{"group": "Possessive pronouns", "category": "Possessivpronomen", "german": "sein", "english": "its", "pronunciation": "zayn"},
{"group": "Possessive pronouns", "category": "Possessivpronomen", "german": "unser", "english": "our", "pronunciation": "un-zer"},
{"group": "Possessive pronouns", "category": "Possessivpronomen", "german": "euer / eure*", "english": "your (You all)", "pronunciation": "oy-er / oy-re"},
{"group": "Possessive pronouns", "category": "Possessivpronomen", "german": "ihr", "english": "their", "pronunciation": "iir"},
{"group": "Possessive pronouns", "category": "Possessivpronomen", "german": "Ihr", "english": "your (formal)", "pronunciation": "iir"},

{"group": "the noun", "category": "das Nomen", "german": "W-Fragen", "english": "W-Questions", "pronunciation": "Vi fragın"},
{"group": "W-Questions", "category": "W-Fragen", "german": "Wer?", "english": "Who?", "pronunciation": "ver"},
{"group": "W-Questions", "category": "W-Fragen", "german": "Was?", "english": "What?", "pronunciation": "vas"},
{"group": "W-Questions", "category": "W-Fragen", "german": "Wo?", "english": "Where?", "pronunciation": "vo"},

];